### ISSUE TITLE
Related SDK architecture armv7 Issue while compiling the application

### ISSUE THREAD

**Issue by aqeelaslam** [relatedcode/Messenger#128]

**Comment by aqeelaslam** [comment]
Any help in it ? Please

**Comment by relatedcode** [comment]
@aqeelaslam A new version will be published soon. This problem will also be covered.

**Comment by aqeelaslam** [comment]
Can you please provide any specific date as when updated version will be released ?

**Comment by relatedcode** [comment]
@aqeelaslam Sorry, but I can't tell you the specific date. I believe the update will be available on this week.

**Comment by aqeelaslam** [comment]
Ok.. I will be waiting for it.. This issue came up when I build app for Adhoc distribution. So I hope new update will be free from such issues.

**Comment by relatedcode** [comment]
@aqeelaslam Sure, it will.
