### ISSUE TITLE
Error when run app !

### ISSUE THREAD

**Issue by dla3jumerah** [relatedcode/Messenger#141]
hi,

i have this error, how i can fixed ?

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Sinch", referenced from:
      objc-class-ref in SINService.o
     (maybe you meant: _OBJC_CLASS_$_SinchService)
  "_SINApplicationDidReceiveRemoteNotification", referenced from:
      -[SINService initWithConfig:] in SINService.o
      -[SINService dealloc] in SINService.o
  "_SINClientDidFailNotification", referenced from:
      -[SINSClientsObserver init] in SINSClientsObserver.o
      -[SINSClientsObserver dealloc] in SINSClientsObserver.o
  "_SINClientDidStartNotification", referenced from:
      -[SINSClientsObserver init] in SINSClientsObserver.o
      -[SINSClientsObserver dealloc] in SINSClientsObserver.o
  "_SINClientWillTerminateNotification", referenced from:
      -[SINSClientsObserver init] in SINSClientsObserver.o
      -[SINSClientsObserver dealloc] in SINSClientsObserver.o
  "_SINRemoteNotificationKey", referenced from:
      -[SINService onDidReceiveRemoteNotification:] in SINService.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by relatedcode** [comment]
@dla3jumerah Please make sure, that you are using the latest version. Furthermore please run both `pod install` and `pod update` before opening the project in Xcode. Lastly please open *app.xcworkspace* instead of *app.xcodeproj*.

Sorry but I don't have any further ideas here. For me it's working perfectly fine.
