### ISSUE TITLE
Firebase Architecture (Messages + Recents)

### ISSUE THREAD

**Issue by alexbelbcn** [relatedcode/Messenger#148]
Why are you using Recents + Messages Architecture? I guess it is better to just use a single tree like "thread" with information of user and message!
threads
   -KfEQV2uczloDssSxtWv
        details
            creation-date: 
            creator-entity-id: 
            last-message-added: 
            name: 
            type: 
            type_v4: 
        messages
            -KfEQW9De3Ji1hiH2ZeE
                  JSON: 
                   date: 
                   payload: 
                   read
                   type: 
                   user-firebase-id: 
            -KfESCtlrY2SjI3gixHJ
            -KfESjPbu5EX3KeVGiNR
         users
            58ELSWzx0AgGe3eyTDDofm5RqOY2
                null: 
            vqtfvXIt7Mg05MVPzBRIElDV4TQ2
                null: 
     -KgeVfj8AeKoCnlI5mcx
    -KgeVw3GF5tyKEFnMOkt
 -KgeafH1WMeQ4xSEJEBC
 -KgeawrY5Ck7qT7Ab8Nr

**Comment by relatedcode** [comment]
@alexbelbcn Will be changed in the future.
