### ISSUE TITLE
DBUsers will become to big when the number of users scale

### ISSUE THREAD

**Issue by itgraule** [relatedcode/Messenger#155]
DBUsers reflect all the database Users of the app, not the users who are in your address book. 
Wha if the app have 1.000.000 of users in the database? Do you need all of theme in your iPhone?
I guess this is not necessary. 
You just need the users that have the app and are in your address book.

Regards

**Comment by relatedcode** [comment]
@itgraule You are right. However this version will work as it is now. I plan to implement a Parse based version in the future. The user management will be refactored then. Anyway, thanks for the feedback. :)
