### ISSUE TITLE
Cannot get other users to load

### ISSUE THREAD

**Issue by hartjosh** [relatedcode/Messenger#164]
Love the previews.  Followed the installation notes completely, but the other users are not showing up in any of the contact lists.  Is there a step missing?

**Comment by hartjosh** [comment]
How should the database rules be set up?

**Comment by relatedcode** [comment]
@hartjosh The user/friend management works very similar to WhatsApp. However the phone numbers need to be exactly the same for the match. Thanks!

**Comment by hartjosh** [comment]
So if User A searches for User B by phone number then User B should show up in User A's contact list?
