### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by bark1n9** [relatedcode/Messenger#176]
Could you please add iPhone X support

Thanks!

**Comment by relatedcode** [comment]
@bark1n9 As far as I see the current implementation is compatible with iPhone X.

**Comment by bark1n9** [comment]
There are some issues such as input toolbar getting into the home indicator and when writing a message the text goes above the input...

**Comment by relatedcode** [comment]
@bark1n9 Would you please shoot a screenshot for me. Thanks!

**Comment by bark1n9** [comment]
![24ff2bc1-312f-4055-9ef5-c685b0b9b787](https://user-images.githubusercontent.com/35073464/36108126-185e5f26-102d-11e8-8d4e-b1d5f2250e6e.png)
![a884e10f-ec42-4a01-ad4e-80d852ae4708](https://user-images.githubusercontent.com/35073464/36108127-18866b7e-102d-11e8-986e-74d843f6213c.png)

**Comment by relatedcode** [comment]
@bark1n9 The latest version seems ok for me.

**Comment by relatedcode** [comment]
![simulator screen shot - iphone x - 2018-02-13 at 11 07 07](https://user-images.githubusercontent.com/5425762/36144364-1d77e758-10ae-11e8-92d1-4c86bfbcf00e.png)

**Comment by relatedcode** [comment]
![simulator screen shot - iphone x - 2018-02-13 at 11 07 11](https://user-images.githubusercontent.com/5425762/36144385-2b03c14e-10ae-11e8-9306-59a74a52cfd6.png)
