### ISSUE TITLE
User cannot be reached by audio/video calls once app running in the background

### ISSUE THREAD

**Issue by qiaoshun8888** [relatedcode/Messenger#178]
Currently user has to stay in the app in order to receive audio/video calls.

If user presses Home button to let the app run in the background, or the phone locked by itself, then user cannot get notifications for incoming audio/video calls.

I haven't looked at the code deeply yet. If it's intentional or it's about the configuration, please let me know. Thanks :)

**Comment by relatedcode** [comment]
@qiaoshun8888 You need to configure your VoIP certificate details properly.

For more info please check:

https://github.com/relatedcode/Messenger#installation

https://www.sinch.com/tutorials/ios8-apps-and-pushkit
