### ISSUE TITLE
Blocking Users

### ISSUE THREAD

**Issue by edisonjoao** [relatedcode/Messenger#179]
I've been trying to find any app that blocks users with firebase as the backend.

I've been stuck for 3 weeks. How did you do it?

I'm just trying to beta test, my app, but apple now requires , in social media apps to have this mechanism of blocking abusive users. 

Please, how did you go about it in your app or how did you set up the logic in firebase and all of that.

**Comment by relatedcode** [comment]
@edisonjoao Drop me a mail and we will discuss the details. info@relatedcode.com
