### ISSUE TITLE
semantic issue on Firebase Auth

### ISSUE THREAD

**Issue by HeZhuu** [relatedcode/Messenger#180]
I'm using Xcode 9.4 and the macOS version is High Sierra 10.13.5.
After pod install, I have a error said ```Sematic Issue```. The error message is 
``` 
Incompatible block pointer types sending 'void (^)(FIRAuthDataResult *__strong, NSError *__strong)' to parameter of type 'FIRAuthResultCallback _Nullable' (aka 'void (^)(FIRUser * _Nullable __strong, NSError * _Nullable __strong)') 
```

**Comment by relatedcode** [comment]
@HeZhuu Please run both 'pod install' and 'pod update'. Thanks!

**Comment by HeZhuu** [comment]
Thank you very much! It was so helpful
