### ISSUE TITLE
Pod Files are Missing

### ISSUE THREAD

**Issue by Ashokdash208** [relatedcode/Messenger#184]
Hello Boss ,
Can you please check once,I am unable to find the pod files (i.e. 
Pod files which are used to access these files are not available)

**Comment by relatedcode** [comment]
Please check the Installation instructions:

https://github.com/relatedcode/Messenger#installation

> 1., Run pod install first (the CocoaPods Frameworks and Libraries are not included in the repo). If you haven't used CocoaPods before, you can get started here. You might prefer to use the CocoaPods app over the command line tool.
