### ISSUE TITLE
PKPushRegistry on iOS13

### ISSUE THREAD

**Issue by oskarko** [relatedcode/Messenger#189]
Hi!
The app does not sound when receive a call and the app is closed or the iPhone is blocked on iOS 13. Are you planning to add this code?

Thanks!

**Comment by relatedcode** [comment]
@oskarko Thanks for the feedback. The call feature update is in progress.

**Comment by relatedcode** [comment]
The Sinch SDK has been update to the latest version. Please check now. Thanks!
