### ISSUE TITLE
Video and audio notifications are not working 

### ISSUE THREAD

**Issue by Manibaratam** [relatedcode/Messenger#191]
I have created voip certificate and uploaded to sinch push configuration still i'm not receiving push notifications

**Comment by theappshed** [comment]
I reckon the problem will be to do with this....

Apps receiving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as pushRegistry:didReceiveIncomingPushWithPayload

Using a handset connected to the Mac, try ringing it from another. You will probably find that the call is received, but it triggers the above exception. Can you confirm?

**Comment by Manibaratam** [comment]
Hello,
I'm receiving audio and video calls if i'm in foreground. If my app is in background i'm not receiving any notifications for audio/video calls. And pushRegistry:didReceiveIncomingPushWithPayload this method also not calling.

**Comment by theappshed** [comment]
I’m exactly the same on iOS 13, but I have a device on iOS12 which receives a notification if it is in the background

I believe the issue is the new requirements set by Apple in iOS13. I’m looking at it at this end to see if I can work it out.

Have you got your VOIP certificate uploaded along with you dev Push certificate in Sinch?

**Comment by Manibaratam** [comment]
I uploaded only VOIP certificate not dev Push certificate in Sinch. Do i need to upload dev Push certificate also?

**Comment by theappshed** [comment]
I believe so. 
However, you must note that for this to work in the background in iOS13 you will need to implement the changes required by Apple:

Apps receiving VoIP pushes must post an incoming call (via CallKit or IncomingCallNotifications) in the same run loop as pushRegistry:didReceiveIncomingPushWithPayload
 There are some notes on this at Sinch - I'll be working through them in the coming days and will keep you updated as to my findings

**Comment by relatedcode** [comment]
Thanks for the feedback. The Sinch VoIP related update is in progress.

**Comment by oskarko** [comment]
Could you make it work @theappshed ?

**Comment by theappshed** [comment]
I've got everything I need working now, except for the backgrounding. I'll be working on that in the next couple of weeks. I'll keep you updated.
The new Sinch version has it built in so it shouldn't take a massive amount of configuring

**Comment by relatedcode** [comment]
The Sinch SDK has been update to the latest version. Please check now. Thanks!
