### ISSUE TITLE
Messages does not apear

### ISSUE THREAD

**Issue by asbis** [relatedcode/Messenger#192]
Everything works great in this project, except showing messages recieved.

<img width="907" alt="Skjermbilde 2020-02-06 kl  08 16 55" src="https://user-images.githubusercontent.com/11362831/73914282-43b05280-48b9-11ea-9fdb-611dbf50eb03.png">

Any clue how that can be solved?

**Comment by relatedcode** [comment]
@asbis Please create the index as it described here:

https://github.com/relatedcode/Messenger/issues/165

**Comment by asbis** [comment]
Thanks for your response.
I probably had an misspell in that code somewhere

Works great now!

**Comment by relatedcode** [comment]
@asbis Great news! :)

**Comment by asbis** [comment]
Just a question. Is there, or is there going to be an android version of this?
If not i will start developing one.

**Comment by relatedcode** [comment]
@asbis I have plans but I cannot promise anything yet...
