### ISSUE TITLE
pod install fail

### ISSUE THREAD

**Issue by derekzhan** [relatedcode/Messenger#193]
` MacBook-Pro  /Volumes/Transcend/swift-code/Messenger/Messenger   master  pod install
Analyzing dependencies
Downloading dependencies
Installing BoringSSL-GRPC (0.0.3)
^@^@^@^@^@^@^@^@^@
[!] Error installing BoringSSL-GRPC
[!] /usr/bin/git clone https://github.com/google/boringssl.git /var/folders/8q/zq32135x7sd6j7mb1_g05bxm0000gn/T/d20200212-7955-k20ky --template=

Cloning into '/var/folders/8q/zq32135x7sd6j7mb1_g05bxm0000gn/T/d20200212-7955-k20ky'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
`

**Comment by relatedcode** [comment]
@derekzhan This is what I can see:

<img width="902" alt="CocoaPods" src="https://user-images.githubusercontent.com/5425762/74340180-bfbd0580-4da5-11ea-8588-6d8f3af0d0c5.png">
