### ISSUE TITLE
Invalid Query in FIRInvalidArgumentException

### ISSUE THREAD

**Issue by ida099** [relatedcode/Messenger#194]
Hello

Thanks fro the new repo, its great for education, I've tried to test it but I ran into this issue ...
Do you have any idea why this error occurs? I've tried to debug it but couldn't find the problem. 
It happens after creating dozens of group chat or chat, not at the beginning. 

*** First throw call stack:
*** Terminating app due to uncaught exception 'FIRInvalidArgumentException', reason: 'Invalid Query. 'in' filters support a maximum of 10 elements in the value array.'

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ida099** [comment]
I think the crash is happens at here 
```
private func createObserverMembers(_ chatIds: [String]) {
		observerMembers?.removeObserver()
		let query = Firestore.firestore().collection("Member")
			.whereField("chatId", in: chatIds)
		observerMembers = DataObserver(query, to: Member.self)
}
```
base on FireStore documentation : 

> Note the following limitations for in and array-contains-any:
in and array-contains-any support up to 10 comparison values.

**Comment by relatedcode** [comment]
@ida099 Thank you for your feedback. Please check the updated codebase.
