### ISSUE TITLE
Crash after clicking "Add Friends"

### ISSUE THREAD

**Issue by LoopingLouieX** [relatedcode/Messenger#199]
After clicking "Add friends/Plus" button the app is crashing in the main thread (AppDelegate).
libc++abi.dylib: terminating with uncaught exception of type NSException

Tested with iOS 13.3 on a real device and with the simulator (demo app).
Happens on all devices with Email Login

**Comment by relatedcode** [comment]
@LoopingLouieX Sorry but I don't experience anything similar. Please provide me some more info. You might copy and paste the content of your Xcode output window here. Thanks!

**Comment by LoopingLouieX** [comment]
Can't reproduce it now!

**Comment by htnha** [comment]
It happens to me on Simulator as well as on Device:
To reproduce:
1. Sign up and sign in
2. Quit the app
3. Open it one again
4. Choose People tab, click on Add Friend

Error:
2020-04-26 09:21:40.489548+0700 Wahup[14252:1697915] [Storyboard] Unknown class _TtC3app14AddFriendsCell in Interface Builder file.
2020-04-26 09:21:40.504743+0700 Wahup[14252:1697915] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITableViewCell 0x7fc689c78dd0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key imageUser.'
*** First throw call stack:
(
    0   CoreFoundation                      0x00007fff23e39f0e __exceptionPreprocess + 350
    1   libobjc.A.dylib                     0x00007fff50ad79b2 objc_exception_throw + 48
    2   CoreFoundation                      0x00007fff23e39ad9 -[NSException raise] + 9
    3   Foundation                          0x00007fff258cccd6 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 325
    4   UIKitCore                           0x00007fff490c8c56 -[UIView(CALayerDelegate) setValue:forKey:] + 171
    5   UIKitCore                           0x00007fff48823833 -[UIRuntimeOutletConnection connect] + 109
    6   CoreFoundation                      0x00007fff23e26222 -[NSArray makeObjectsPerformSelector:] + 242
    7   UIKitCore                           0x00007fff48820a1c -[UINib instantiateWithOwner:options:] + 2192
    8   UIKitCore                           0x00007fff48dc40ee -[UITableView _dequeueReusableViewOfType:withIdentifier:] + 610
    9   UIKitCore                           0x00007fff48dc471a -[UITableView _dequeueReusableCellWithIdentifier:forIndexPath:usingPresentationValues:] + 496
    10  UIKitCore                           0x00007fff48dc44f6 -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:] + 91
    11  Wahup                               0x00000001018d46aa $s5Wahup14AddFriendsViewC05tableD0_12cellForRowAtSo07UITableD4CellCSo0jD0C_10Foundation9IndexPathVtF + 330
    12  Wahup                               0x00000001018d49c5 $s5Wahup14AddFriendsViewC05tableD0_12cellForRowAtSo07UITableD4CellCSo0jD0C_10Foundation9IndexPathVtFTo + 165
    13  UIKitCore                           0x00007fff48dde236 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 867
    14  UIKitCore                           0x00007fff48da7916 -[UITableView _updateVisibleCellsNow:] + 3010
    15  UIKitCore                           0x00007fff48dc75ee -[UITableView layoutSubviews] + 194
    16  UIKitCore                           0x00007fff490c9848 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2478
    17  QuartzCore                          0x00007fff2b4ae3f0 -[CALayer layoutSublayers] + 255
    18  QuartzCore                          0x00007fff2b4b457b _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 523
    19  UIKitCore                           0x00007fff490b48c8 -[UIView(Hierarchy) layoutBelowIfNeeded] + 573
    20  UIKitCore                           0x00007fff48440ceb -[_UISheetPresentationController _sheetLayoutInfoLayout:] + 48
    21  UIKitCore                           0x00007fff4843e42b -[_UISheetLayoutInfo _layout] + 360
    22  UIKitCore                           0x00007fff48442b40 __54-[_UISheetPresentationController transitionWillBegin:]_block_invoke_2 + 52
    23  UIKitCore                           0x00007fff490bb8a8 +[UIView(Animation) performWithoutAnimation:] + 84
    24  UIKitCore                           0x00007fff48442a7d __54-[_UISheetPresentationController transitionWillBegin:]_block_invoke.341 + 120
    25  UIKitCore                           0x00007fff4854dc35 -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] + 294
    26  UIKitCore                           0x00007fff48549fd7 -[_UIViewControllerTransitionContext __runAlongsideAnimations] + 263
    27  UIKitCore                           0x00007fff490bb6d1 __63+[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:]_block_invoke + 16
    28  UIKitCore                           0x00007fff4908d0dc -[UIViewAnimationState _runAlongsideAnimations] + 24
    29  UIKitCore                           0x00007fff4908be56 -[UIViewAnimationState pop] + 37
    30  UIKitCore                           0x00007fff49089276 +[UIViewAnimationState popAnimationState] + 62
    31  UIKitCore                           0x00007fff490bd0ee +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] + 650
    32  UIKitCore                           0x00007fff490bd623 +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] + 99
    33  UIKitCore                           0x00007fff49084859 __50-[UITransitionView _startTransition:withDuration:]_block_invoke.169 + 66
    34  UIKitCore                           0x00007fff490bdb18 +[UIView(UIViewAnimationWithBlocks) conditionallyAnimate:withAnimation:layout:completion:] + 76
    35  UIKitCore                           0x00007fff4908423d -[UITransitionView _startTransition:withDuration:] + 699
    36  UIKitCore                           0x00007fff49083d10 -[UITransitionView transition:fromView:toView:removeFromView:] + 2760
    37  UIKitCore                           0x00007fff4854602b -[UIViewControllerBuiltinTransitionViewAnimator animateTransition:] + 1220
    38  UIKitCore                           0x00007fff4854e80a ___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 59
    39  UIKitCore                           0x00007fff4867043f +[UIInputResponderController _pinInputViewsForInputResponderController:onBehalfOfResponder:duringBlock:] + 99
    40  UIKitCore                           0x00007fff4854e799 ___UIViewControllerTransitioningRunCustomTransition_block_invoke.645 + 180
    41  UIKitCore                           0x00007fff490bb5d3 +[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 175
    42  UIKitCore                           0x00007fff4854e61f _UIViewControllerTransitioningRunCustomTransition + 553
    43  UIKitCore                           0x00007fff48430ecf __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.465 + 2598
    44  UIKitCore                           0x00007fff48bd118e _runAfterCACommitDeferredBlocks + 352
    45  UIKitCore                           0x00007fff48bc191c _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
    46  UIKitCore                           0x00007fff48bf2075 _afterCACommitHandler + 85
    47  CoreFoundation                      0x00007fff23d9d2a7 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
    48  CoreFoundation                      0x00007fff23d97d5e __CFRunLoopDoObservers + 430
    49  CoreFoundation                      0x00007fff23d982aa __CFRunLoopRun + 1226
    50  CoreFoundation                      0x00007fff23d97ac4 CFRunLoopRunSpecific + 404
    51  GraphicsServices                    0x00007fff38b2fc1a GSEventRunModal + 139
    52  UIKitCore                           0x00007fff48bc7f80 UIApplicationMain + 1605
    53  Wahup                               0x000000010192770b main + 75
    54  libdyld.dylib                       0x00007fff519521fd start + 1
