### ISSUE TITLE
Not connecting upon production

### ISSUE THREAD

**Issue by theappshed** [relatedcode/Messenger#201]
Evening!
Have you checked a version of this working in production?

I'm using the latest version of Sinch, and the code here which includes the iOS13 callback. Certificates are all created and uploaded correctly (it was working perfectly in development, but as soon as it went to production it stopped)

I've uploaded an app for release and it rings out from the caller end, but doesn't connect at the recipient end.

Not sure if you or anyone else is experiencing this?
I have Sinch looking at their end to see if I've got something wrong, but if you know anything this end that'd be great.

Many thanks,
Steve

**Comment by Manibaratam** [comment]
Hey,
Calling functionality is working in simulator?, just to check whether functionality is working or not?

**Comment by theappshed** [comment]
Hi Manibaratam, 

I have it working perfectly in development, though you should use an actual device to test if possible.
My issue is when it is going into production. Sinch have confirmed that on the test calls, they didn't receive a device pushprofile

**Comment by Manibaratam** [comment]
Hi theappshed,
Thanks for the info

**Comment by theappshed** [comment]
OK everyone there is a line of code in the AppDelegate.swift file:
push = Sinch.managedPush(with: .development)

You need to swap these between development and production, AND have the correct APNS and VOIP certificates at Sinch for this to work... I think. Just uploading an archive now - I'll report back shortly

**Comment by Manibaratam** [comment]
In real device calling is not working in foreground, its working only in background . Am i missing anything?

**Comment by relatedcode** [comment]
This seems to be obsolete now.
