### ISSUE TITLE
Open ConversationView of specific user

### ISSUE THREAD

**Issue by LoopingLouieX** [relatedcode/Messenger#205]
Is it possible to open the message view (where the conversation between X & Y is shown) of a specific user without opening the "ActionNewChat" function ?
So what I want to do exactly:
 -> Click on a button
 -> This button is directly opening the specific conversation window between User X and Y.

The Firebase ID's are known of each other and both are Friends too!
So all I want is just to avoid the additional window where all the friends are shown.
If no conversation is available, then the according data(Firebase and Realm) should be created also.

Thanks!

**Comment by relatedcode** [comment]
@LoopingLouieX Sure. The `ProfileView` `actionChatPrivate` method does exactly what you need.

<img width="698" alt="actionChatPrivate" src="https://user-images.githubusercontent.com/5425762/80918175-def37f80-8d63-11ea-841f-f00d2be85f96.png">
