### ISSUE TITLE
How to add find people to chat with?

### ISSUE THREAD

**Issue by samp50** [relatedcode/Messenger#208]
How can I add people to chat with in the app? I have two iPhones running the app with Xcode, and have verified that my Google Firebase .plist is working. When I try to select a new user, I cannot find anyone in the list of people. How are users initially discovered on the app, and where is this functionality in the app?

**Comment by Lalithsai853** [comment]
same issue as stated above.. would like to know if there is a fix

**Comment by bark1n9** [comment]
Hi, I'm experiencing the same issue, were you able to fix it?

**Comment by rileywilky** [comment]
Were any of you able to solve this?

**Comment by bark1n9** [comment]
@rileywilky No :(

**Comment by rileywilky** [comment]
I think I solved the issue. Or, at least this fixed the problem for me. 

You need to use the basic FireStore Rules that are defined in the documentation, not the rules that are default included when you create the project. 

Here are the basic rules to use in your project to get it functioning assuming you have a working connection with Firebase: 

// Allow read/write access on all documents to any user signed in to the application
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}

**Comment by techousplus** [comment]
@rileywilky That works, but when I send a message the message doesn't seem to be received on the other end.

**Comment by bark1n9** [comment]
@rileywilky This works, but when I send a message the other device doesn't receive it.

**Comment by bark1n9** [comment]
@rileywilky Nevermind, I forgot to create Firestore Index. It's working now.

**Comment by bark1n9** [comment]
@rileywilky Now I can't seem to get Sinch calls to work. Were you able to implement it succesfully?
