### ISSUE TITLE
Docker Comp[ose Error

### ISSUE THREAD

**Issue by Tabarane** [relatedcode/Messenger#225]
after downloading the yaml file , i get the below error after starting compose up

```
docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'config_files'
Unsupported config option for services: 'postgres'

```

i modified only email name passwords nothing else, what am i doing wrong?

**Comment by relatedcode** [comment]
@Tabarane Please be careful, that the docker-compose file is sensitive to indentation. If you have a chance, then please send the following information in private:

- the version of docker you are using
- did you preserve the indentation within the docker compose file
- share the docker-compose file if possible

Thanks!
