### ISSUE TITLE
Deployment Instructions and Customization Options

### ISSUE THREAD

**Issue by sanjeev-lmg** [relatedcode/Messenger#233]
Hello team,

We're encountering difficulties in running/deploying this locally. Could you please provide instructions on how to deploy/run it locally and customize it to meet our requirements? Additionally, we'd appreciate information on any associated costs. Adding to it is there any Geo restrictions like if the restriction is there for countries like China or GCC?

Thank you,
Sanjeev

**Comment by jacklin719772** [comment]
hello team，url -o docker-compose.yml https://gqlite.com/relatedchat/docker-compose.yml,it can't work well,can u help me?
Thank you,
Jack Lin

**Comment by relatedcode** [comment]
Please try this:

```
curl -o docker-compose.yml https://rel.codes/messenger/docker-compose.yml

docker compose up -d
```

**Comment by relatedcode** [comment]
@sanjeev-lmg You can run the code wherever you want. You can control everything. It's using Docker.
